name: Build Wasm
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # For WAT compilation
      - name: Install WABT
        run: sudo apt-get install -y wabt
      - name: Compile WAT to Wasm
        run: wat2wasm grayscale.wat -o grayscale.wasm

      # OR For AssemblyScript compilation
      # - run: npm install && npm run asbuild

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: grayscale.wasm
