name: Build CWT WASM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install AssemblyScript
        run: npm install --save-dev assemblyscript

      - name: Compile WASM
        run: |
         npx asc cwt.ts \
            --outFile diag.wasm \
            --initialMemory 8500 \
            --maximumMemory 8500 \
            --importMemory \
            --runtime stub \
            --use abort= \
            --optimize
            
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasm-build
          path: cwt.wasm
