name: Build CWT
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install assemblyscript
      - run: |
          npx asc index.ts -o cwt.wasm \
          --optimize --noExportRuntime --runtime stub \
          --initialMemory 8192 --maximumMemory 8192 \
          --explicitStart
      - uses: actions/upload-artifact@v4
        with:
          name: cwt-wasm
          path: cwt.wasm
