name: Build CWT
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install assemblyscript
      - run: |
         npx asc cwt.ts -o cwt.wasm \
          --optimize \
          --initialMemory 8192 \
          --maximumMemory 8192 \
          --noExportRuntime \
          --runtime stub \
          --exportRuntime \
          --exportStart _start
      - uses: actions/upload-artifact@v4
        with:
          name: cwt-wasm
          path: cwt.wasm
