name: Build CWT WASM
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install assemblyscript
      - name: Compile
        run: |
          npx asc index.ts -o cwt.wasm \
          --optimize \
          --initialMemory 8000 \
          --maximumMemory 8000 \
          --noExportRuntime \
          --runtime stub \
          --explicitStart
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cwt-binary
          path: cwt.wasm
